### ISSUE TITLE
Import Maps from dlh_googlemaps

### ISSUE THREAD

**Issue by hinzke** [netzmacht/contao-leaflet-maps#91] opened 2020-08-18 12:29 UTC
Is there a workaround, how can i import Maps, with Marker etc from dlh_googlemaps to contao-leaflet-maps

**Comment by dmolineus** [comment] 2020-08-18 15:22
Feature isn't implemented yet (See #64). As a workaround you can create a custom migration script or recreate the data. Closing this as it's a duplicate of #64.

**Closed by dmolineus** 2020-08-18 15:22 UTC
